### ISSUE TITLE
Link to GIS files for districts

### ISSUE THREAD

**Issue by astronouth7303** [citizenlabsgr/elections-api#105]
Data source:
* Information: https://www.michigan.gov/documents/cgi/framework_product_documentation_2016_536048_7.pdf
* Downloads: https://gis-michigan.opendata.arcgis.com/

Tools:
* GeoDjango https://docs.djangoproject.com/en/2.2/ref/contrib/gis/tutorial/
* PostGIS

GeoDjango (and its dependencies) can import geometry from Shapefiles available for download.

Data layers available:
* School Districts
* Cities & Townships
* State House Districts
* State Senate Districts
* US Congressional Districts
* Public Land Survey stuff
* "Topo Quad Boundaries"

Notably, "Precincts" are not given

**Comment by jessachalla** [comment]
Have
School Districts
Cities & Townships
Villages
State House Districts
State Senate Districts
US Congressional Districts
Precincts
Counties

**Comment by jessachalla** [comment]
Have 
Cities
Intermediate School Districts
Metropolitan Planning Organizations

**Comment by jacebrowning** [comment]
🎉 https://citizenlabs.maps.arcgis.com/apps/ZoneLookup/index.html?appid=d504b6d2bfd646f6a76cfbe9ff4294d6
