### ISSUE TITLE
Political party is wrong on some candidates

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/elections-api#76]
https://webapps.sos.state.mi.us/MVIC/SampleBallot.aspx?d=1828&ed=676 has the wrong political party listed for senators: http://michiganelections.io/api/positions/?precinct_id=1217

**Comment by jacebrowning** [comment]
We're also going to need to version the parser to force a reparse.

**Comment by jacebrowning** [comment]
@joshfriend I think this is fixed now. Can you spot check your own ballot?

You can look up your `precinct_id` (for this API) here: http://michiganelections.io/api/registrations/

Then request the positions from your ballot here: http://michiganelections.io/api/positions/?precinct_id=99999

**Comment by joshfriend** [comment]
Yes, they seem to match now

http://michiganelections.io/api/positions/?precinct_id=5919
https://webapps.sos.state.mi.us/MVIC/SampleBallot.aspx?d=5923&ed=676&bl=

**Comment by jacebrowning** [comment]
Thanks!

The issue was that the logic to skip over gubernatorial candidates' running mates was being used for all positions so instead of mapping `R D G L ...` it was mapping `R R D D ...`.
